name: Manual Vulnerability Check Trigger

on:
  workflow_dispatch:

env:
  TERM: dumb
jobs:
  call-vuln-check:
    # uses: ./.github/workflows/vuln-check.yaml
    uses: ymorimo/scalar-actions/.github/workflows/vuln-check-reusable.yaml@add-vuln-check
    with:
      target-ref: ${{ github.ref_name }}
      images: '[["ScalarDB Schema Loader", "scalardb-schema-loader"]]'
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      SLACK_SECURITY_WEBHOOK_URL: ${{ secrets.SLACK_SECURITY_WEBHOOK_URL }}
