name: Vulnerability Check

on:
  workflow_call:
    inputs:
      target-ref:
        description: 'Target ref (branch, tag, release) to scan'
        required: true
        type: string
        default: 'main'
      find-latest-release:
        description: 'Flag to find the latest version for specified `target-ref`'
        required: false
        type: boolean
        default: false
    secrets:
      SLACK_SECURITY_WEBHOOK_URL:
        required: false

jobs:
  vuln-check:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        id: build-docker-image
        # uses: scalar-labs/actions/.github/actions/build-docker-images@main
        uses: ymorimo/scalar-actions/.github/actions/build-docker-images@main
        with:
          target-ref: ${{ inputs.target-ref }}
          find-latest-release: ${{ inputs.find-latest-release }}

      - name: Check Docker image
        id: check-docker-image
        run: |
          # list=$(echo ${{ steps.build-docker-image.outputs.docker-images }} | tr ',' '\n')
          # echo $list
          # echo ref-scalardb-schema-loader=$(echo $list | grep scalardb-schema-loader) >> $GITHUB_OUTPUT

          # Since scalardb build produces only one image, we can specify the output as it is.
          echo ref-scalardb-schema-loader=${{ steps.build-docker-image.outputs.docker-images }} >> $GITHUB_OUTPUT

      - name: Vulnerability check for ScalarDB Schema Loader
        # uses: scalar-labs/actions/.github/actions/vlun-check@main
        uses: ymorimo/scalar-actions/.github/actions/vuln-check@main
        with:
          image-ref: ${{ steps.check-docker-image.outputs.ref-scalardb-schema-loader }}
          slack-webhook-url: ${{ secrets.SLACK_SECURITY_WEBHOOK_URL}}

    # uses: ymorimo/scalar-actions/.github/workflows/vuln-check-reusable.yaml@main
    # with:
    #   target-ref: ${{ inputs.target-ref }}
    #   find-latest-release: ${{ inputs.find-latest-release }}
    #   images: '[["ScalarDB Schema Loader", "scalardb-schema-loader"]]'
    #   version-command: "./gradlew :core:properties -q | grep version: | awk '{print $2}'"
    # secrets:
    #   CR_PAT: ${{ secrets.CR_PAT }}
    #   SLACK_SECURITY_WEBHOOK_URL: ${{ secrets.SLACK_SECURITY_WEBHOOK_URL }}
