name: Vulnerability Check

on:
  workflow_call:
    inputs:
      target-ref:
        description: 'Target ref (branch, tag, release) to scan'
        required: true
        type: string
        default: 'main'
      find-latest-release:
        description: 'Flag to find the latest version for specified `target-ref`'
        required: false
        type: boolean
        default: false
    secrets:
      SLACK_SECURITY_WEBHOOK_URL:
        required: false

jobs:
  vuln-check:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        id: build-docker-image
        # uses: scalar-labs/actions/.github/actions/build-docker-images@main
        uses: ymorimo/scalar-actions/.github/actions/build-docker-images@main
        with:
          target-ref: ${{ inputs.target-ref }}
          find-latest-release: ${{ inputs.find-latest-release }}

      - name: Check Docker image
        id: check-docker-image
        run: |
          list='${{ steps.build-docker-images.outputs.docker-images }}'
          echo ref-scalardb-schema-loader=$(grep scalardb-schema-loader <<< "$list") >> $GITHUB_OUTPUT

      - name: Run ScalarDB Schema Loader vulnerability check
        continue-on-error: true
        # uses: scalar-labs/actions/.github/actions/vlun-check@main
        uses: ymorimo/scalar-actions/.github/actions/vuln-check@main
        with:
          image-ref: ${{ steps.check-docker-image.outputs.ref-scalardb-schema-loader }}
          slack-webhook-url: ${{ secrets.SLACK_SECURITY_WEBHOOK_URL}}
