name: Vulnerability Check

on:
  workflow_call:
    inputs:
      target-ref:
        description: 'Target ref (branch, tag, release) to scan'
        required: true
        type: string
        default: 'main'
      find-latest-release:
        description: 'Flag to find the latest version for specified `target-ref`'
        required: false
        type: boolean
        default: false
    secrets:
      SLACK_SECURITY_WEBHOOK_URL:
        required: false

jobs:
  vuln-check:
    runs-on: ubuntu-latest

    steps:
      - name: Build ScalarDB Schema Loader Docker image
        id: build-docker-images
        uses: scalar-labs/actions/.github/actions/build-docker-images@vuln-check-composite-actions # TODO: @main
        with:
          target-ref: ${{ inputs.target-ref }}
          find-latest-release: ${{ inputs.find-latest-release }}

      - name: Find Docker image ref
        id: find-docker-image-ref
        run: |
          list='${{ steps.build-docker-images.outputs.docker-images }}'
          echo ref-scalardb-schema-loader=$(grep scalardb-schema-loader <<< "$list") >> $GITHUB_OUTPUT

      - name: Check ScalarDB Schema Loader Docker image for vulnerabilities
        continue-on-error: true
        uses: scalar-labs/actions/.github/actions/vuln-check@vuln-check-composite-actions # TODO: @main
        with:
          image-ref: ${{ steps.find-docker-image-ref.outputs.ref-scalardb-schema-loader }}
          slack-webhook-url: ${{ secrets.SLACK_SECURITY_WEBHOOK_URL}}
